version: '3'
services:
  server:
    build:
      context: './'
      dockerfile: 'Dockerfile'
    restart: always
    container_name: asr-demo-server
    ports:
      - "80:443"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ['gpu']